### ISSUE TITLE
Gradient and Radar as Tech Radar

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#106]
新需求：
1. 流程图除了自己配颜色，能否提供渐变色？用于描述递进关系。（渐变色、随机色等）
2. 类似技术雷达、读书雷达的Radar。
3. 简易看板：swimlane、stage、cards

**Comment by phodal** [comment]
1. 目前是有默认色的
3. 已经有卡了 https://github.com/phodal/ledge/issues/54

**Comment by phodal** [comment]
技术雷达组件：https://github.com/zalando/tech-radar

**Comment by phodal** [comment]
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/472311/79089595-43c94480-7d79-11ea-9f14-de17e6a619b7.png">
