### ISSUE TITLE
[docs style] 文档阅读体验提升

### ISSUE THREAD

**Issue by giscafer** [phodal/ledge#107]
**Is your feature request related to a problem? Please describe.**

- 文档目录样式
- 文档内容markdown渲染样式

**Describe the solution you'd like**

### 语雀文档的目录效果

![image](https://user-images.githubusercontent.com/8676711/79121295-8a459000-7dc7-11ea-88ed-793411508304.png)

可访问长文看目录效果：https://www.yuque.com/wangpingan/cute-frontend/cb1u91

（语雀文档的布局也不错）

### vue 文档样式效果

![image](https://user-images.githubusercontent.com/8676711/79121474-ffb16080-7dc7-11ea-82f8-23ba084e67d2.png)

https://cn.vuejs.org/

[vuepress](https://github.com/vuejs/vuepress) 好像有现成的主题模板（社区应该也有人写主题），也是基于markdown渲染的，可以考虑能不能把主题样式拿过来改。

### angular 文档目录效果

![image](https://user-images.githubusercontent.com/8676711/79121648-59b22600-7dc8-11ea-9acc-09a25bab2ff2.png)

ng 的目录也可以吧。

## 内容 markdown 样式

默认的markdown渲染的字体和 title 的样式不够美观，可以看能不能用社区一些现有的静态网站编译的markdown 主题样式修改使用。比如 vuepress、Hexo 等（之前见过一些，一时想不起来别的）

**Comment by phodal** [comment]
新侧边栏：https://app.zeplin.io/project/5e88a6eccac5a22021671ff1/screen/5e987f8737ca347bb959624e

<img width="957" alt="image" src="https://user-images.githubusercontent.com/472311/79524891-33280f80-8094-11ea-8506-8d2583b18579.png">
