### ISSUE TITLE
Radar issue

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#109]
首先感谢响应需求~🙏

1. Radar的小圈序号，当进入序号范围时，鼠标悬停显示序号内容，但当鼠标停在序号上时，显示可以link到：https://devops.phodal.com/#{象限名称}，点击找不到会返回主页。

2. 第四象限样式颜色过浅
![image](https://user-images.githubusercontent.com/22843012/79132680-56756500-7ddd-11ea-90e0-154b192cdaed.png)

3. 雷达可以配多余4个象限不？
![image](https://user-images.githubusercontent.com/22843012/79133301-5fb30180-7dde-11ea-9b9b-be537338140f.png)

**Comment by phodal** [comment]
多于四个的话，你要怎么设计？
