### ISSUE TITLE
Ledge helper editor code style

### ISSUE THREAD

**Issue by giscafer** [phodal/ledge#112]
可以考虑 markdown 语法高亮样式，还支持快捷键操作。

以前封装过一个ace的组件，https://github.com/giscafer/ngx-ace-tern

![image](https://user-images.githubusercontent.com/8676711/79213655-203af280-7e7c-11ea-86ad-2ea85554e4f9.png)

**Comment by phodal** [comment]
可以，可以，你要不直接集成进来？

**Comment by giscafer** [comment]
@phodal 嗯，有空我集成一下。
