### ISSUE TITLE
Language menu issue

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#116]
1. 中文模式下，切换语言应显示为中文。另外，more link到 ledge的issue页，是designed so不？
![image](https://user-images.githubusercontent.com/22843012/79419026-8cd30000-7fe8-11ea-9c3a-ac7fbd0a70cd.png)

2. 专栏选中样式错位
![image](https://user-images.githubusercontent.com/22843012/79420476-9447d880-7feb-11ea-9f56-ab8e2397066f.png)

**Comment by phodal** [comment]
1. 如果有更多的语言需要来可以来提 issue

**Comment by ConnieYXN** [comment]
> 1. 如果有更多的语言需要来可以来提 issue

哇，出发点很好，比较含蓄呢，没get到。。
