### ISSUE TITLE
Left menu style suggestion

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#117]
左侧菜单栏建议不要滚动条，显示不下可以显示 ... ，再加上鼠标悬停显示全部。

![image](https://user-images.githubusercontent.com/22843012/79420725-146e3e00-7fec-11ea-8074-7e68d4ae4bde.png)

**Comment by phodal** [comment]
refs: https://codepen.io/drygiel/pen/LXmPZz
