### ISSUE TITLE
Unexpected black background displayed

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#120]
首页，当从页头缓慢滑动鼠标，或者使用键盘从页头向下滚屏，滚至“DevOps 相关资源”时，会有黑色背景显示，再往下滚一点就消失了。

![image](https://user-images.githubusercontent.com/22843012/79422483-885e1580-7fef-11ea-9e59-62728e5138bf.png)

**Comment by LiuuY** [comment]
因为 Contributors 进入 Viewport 的时候才渲染，导致一开始「DevOps 相关资源」在 Footer 位置。
