### ISSUE TITLE
Ledge Framework 提取

### ISSUE THREAD

**Issue by phodal** [phodal/ledge#123]
Refs: https://angular.io/guide/creating-libraries#creating-libraries

AC:

支持提取两种类型的文档。

 - 单一文件渲染。现有的 Markdown Render Component
 - 多文件渲染。现有的 Case Study

可以支持：

 - 使用 Ledge Framework 时，只需要配置 + 文档即可

考虑支持：

 - 支持 Web Components 的方式引入。即  [Angular Elements](https://angular.io/guide/elements)
 - 支持 GitHub 的 Jekyll Remote Theme

潜在的问题：

 - 小范围的 CSS 重构
 - 替换 Material Design Icon
 - 替换 Material Design DrawLayout
 - 名称？ `@ledge-framework/view`???

**Comment by hylerrix** [comment]
对 Ledge Framework 有个新想法：支持中英批注的插件，如下图，点击中文后展示翻译前的中文。

![](https://user-images.githubusercontent.com/19285461/81177025-9db7d580-8fd8-11ea-818e-d6a860a5390f.png)

**Comment by phodal** [comment]
done https://github.com/ledge-framework/engine/
