### ISSUE TITLE
操作手册页面下tool_bar收起后无法固定，左侧栏换行

### ISSUE THREAD

**Issue by spacexzm** [phodal/ledge#13]
### 问题1：
调试模式下，调试工具在底部，右侧出现两个滚动条。当操作手册页面tool_bar收起后，再次上拉展开tool_bar会自动收起。
![image](https://user-images.githubusercontent.com/33437599/77998206-5009d680-7363-11ea-8eb6-be0e97475291.png)
调试工具在右侧或左侧，底部出现两个滚动条
![image](https://user-images.githubusercontent.com/33437599/77998300-762f7680-7363-11ea-9810-263fa31dc15e.png)
### 问题2：
侧栏换行问题，浏览器宽高比1440*900
![image](https://user-images.githubusercontent.com/33437599/77998441-b131aa00-7363-11ea-8eb9-0c1ec66fccdf.png)

**Comment by phodal** [comment]
fixed with #12
