### ISSUE TITLE
希望能增加安全和前端相关的 checklists 

### ISSUE THREAD

**Issue by zhengxs2018** [phodal/ledge#132]
**Is your feature request related to a problem? Please describe.**
这是一个功能性请求，非 bug

**Describe the solution you'd like**

目前前端也存在服务端维护的需求，因为很多小公司的 nodejs 就是前端自己发布的，但是因为很多前端其实对这块不太熟悉，也不太重视，而且有些公司后端和技术负责人也不太愿意管理这块，所以对于前端来说，其实还是很有必要的

**Describe alternatives you've considered**

以前基本上都是参考各种文章自己捣鼓，但是也不是很全，基本就是想到什么，弄什么，所以也没太多的可参考性

**Additional context**

这是可供参考的示例

https://github.com/shieldfy/API-Security-Checklist
https://github.com/thedaviddias/Front-End-Checklist

**Comment by phodal** [comment]
中文版本的 API checklist： https://github.com/shieldfy/API-Security-Checklist/blob/master/README-zh.md

**Comment by zhengxs2018** [comment]
我知道有，就是想多弄点，排列一个优先级到网站上，这样可以提供更多参考

**Comment by hylerrix** [comment]
> 中文版本的 API checklist： https://github.com/shieldfy/API-Security-Checklist/blob/master/README-zh.md

安全的这个我看没加，还需要加吗？我可以 PR 一下 🧜‍♂️

**Comment by phodal** [comment]
我记得他已经在吃了，你要不试试 DevSecOps 流水线的，比如：https://github.com/phodal/ledge/issues/139

**Comment by hylerrix** [comment]
> 我记得他已经在加了，你要不试试 DevSecOps 流水线的，比如：#139

😹搜了下 DevSecOps 是 DevOps + 安全防护，知识盲区，我先不接了，有大前端相关的记得喊我

**Comment by phodal** [comment]
@hylerrix 因为是盲区，所以你可以先接了试试看，提升一下自己

**Comment by phodal** [comment]
其实你把中文版的理一理就有了：https://mp.weixin.qq.com/s/s6P7Ucv1V2oWknfkvucMOw

**Comment by hylerrix** [comment]
> 其实你把中文版的理一理就有了：https://mp.weixin.qq.com/s/s6P7Ucv1V2oWknfkvucMOw

有中文版就不客气了，这俩天尝试 PR 一下

P.S. 主要是 DevOps 才准备通过 Ledge 去了解，步子迈太大去搞翻译得不偿失 🤡

**Comment by phodal** [comment]
fixed with #178
