### ISSUE TITLE
SSG 首页没有渲染 Menu

### ISSUE THREAD

**Issue by LiuuY** [phodal/ledge#138]
## Current Behavior?
![image](https://user-images.githubusercontent.com/14286374/79757384-9ba21580-834e-11ea-8ebd-502720c8c17c.png)

## Expected Behavior?
应该渲染出顶部的 Menu

**Comment by ExDevilLee** [comment]
@LiuuY 图上的问题最新版已经不存在了

**Comment by LiuuY** [comment]
我这边看还是有。 @ExDevilLee 
![frontpage](https://user-images.githubusercontent.com/14286374/80306957-cda4f300-87f8-11ea-9407-f68baad7d43a.gif)
![image](https://user-images.githubusercontent.com/14286374/80306977-e6150d80-87f8-11ea-91e2-7906c8cc4406.png)

**Comment by ExDevilLee** [comment]
@LiuuY 抱歉，我没有这样看，刚才试了下，确实还存在

**Comment by phodal** [comment]
SSR 导致的 reponsive 问题
