### ISSUE TITLE
内容显示错乱:https://devops.phodal.com/home

### ISSUE THREAD

**Issue by LeeRnnGii** [phodal/ledge#14]
issue1:
链接：https://devops.phodal.com/home
![chrome_issue](https://user-images.githubusercontent.com/32997140/78005406-18ecf280-736e-11ea-870c-66f3fea91afb.gif)
问题：description长文本内容显示不全，且超出色块
浏览器版本：
![chrome_version](https://user-images.githubusercontent.com/32997140/78005703-8731b500-736e-11ea-9bb8-6e24816247cb.PNG)
issue2:
链接：https://devops.phodal.com/home
![firefox_issue](https://user-images.githubusercontent.com/32997140/78005767-9f093900-736e-11ea-87eb-3b5e5cfecfbf.gif)
问题：category-selector内容显示错位
浏览器版本：
![firefox_version](https://user-images.githubusercontent.com/32997140/78006109-20f96200-736f-11ea-9f31-7d1454858b88.PNG)

**Comment by phodal** [comment]
@LeeRnnGii 试试修复？

**Comment by LeeRnnGii** [comment]
我尝试修复了**issue1**的问题，采用如下解决方法：
![fixed](https://user-images.githubusercontent.com/32997140/78030611-f1f5e700-7394-11ea-978f-c3394144b869.PNG)
但却发现了新问题
**issue3**:在添加`overflow: auto`，即增加滑动条后，可能会导致体验问题。
详述：以元素周期表116号元素为例，该元素描述为长文本，在修复**issue1**后可通过滑动条查看。
![issue3](https://user-images.githubusercontent.com/32997140/78031586-54031c00-7396-11ea-9c71-52d645b8a836.PNG)
正常情况下，鼠标可移动滑动条查看剩余内容。但此时，当鼠标移向色块时，色块却只能展示最后在元素周期表中元素的内容，从而无法查看余下内容。
![issue3](https://user-images.githubusercontent.com/32997140/78032699-01c2fa80-7398-11ea-99c7-d698d430dbfc.gif)

**Comment by phodal** [comment]
这个地方理论上在点下去的时候，要变成弹窗之类的，如 #6 所示。所以 你可以先给个 PR
