### ISSUE TITLE
网图默认值issue

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#144]
Current Behavior：当右侧滑块未全部设置时，网图不显示图线。
Expected Behavior：建议初始化网图和滑块的默认值。

![image](https://user-images.githubusercontent.com/22843012/79935858-8cbf7e00-8488-11ea-8d25-9720caed44f5.png)

**Comment by phodal** [comment]
这个应该只限于度量页面的，别的网图是不受影响的
