### ISSUE TITLE
建议：“最佳实践”的目录命名建议为名词复数形式

### ISSUE THREAD

**Issue by ExDevilLee** [phodal/ledge#165]
ledge/src/assets/docs/ 目录下其他的项目是名词复数形式，例如：

- casestudies
- checklists
- solutions

建议：practise --> practises

**Comment by phodal** [comment]
欢迎来 PR 😆

**Comment by ExDevilLee** [comment]
哈哈，好的，我尝试修改下

**Comment by ExDevilLee** [comment]
抱歉，经过一些尝试后发现在没有熟悉项目结构的前提下，这个rename活动并不是那么简单。

有如下疑问：
1、请问这个项目建议用哪个IDE来编辑？推荐的settings是什么呢？
2、我本地rename后如何验证整体项目的正确性呢？（担心错改或者漏改造成的错误）

**Comment by phodal** [comment]
我用的是 IDEA / WebStorm，它用到的地方是在 `practise.component.ts`。

验证的话，需要启动 server，然后点击『最佳实践』的菜单，进行验证。

**Comment by ExDevilLee** [comment]
好的，我找时间试一下，多谢解答~

**Comment by ExDevilLee** [comment]
fixed by #169
