### ISSUE TITLE
Skill-tree feature needs improvement

### ISSUE THREAD

**Issue by hylerrix** [phodal/ledge#168]
## Feature Request

根据中英文版 DevOps Map, 刚才完善了 DevOps 相关的 skilltree 文档, 提了[一个 PR #167 ](https://github.com/phodal/ledge/pull/167)

但是有几个问题需要反馈并解决: 🧐

* 反馈 1: skilltree 路由需要支持 devops、frontend、backend 子路由
  * 这样可以拓展以后的前端后端路线图
* 反馈 2: graphviz 画出来的图超出范围后有问题
  * 不太熟悉 graphviz, 目前渲染后的图超出展示面积且无法拖动
  * 同时默认渲染的图排列并不紧凑(有的向左拓展有的向右拓展)
* 反馈 3：checklists 检查清单子路由能否支持英文名而不是 id 号

同时我还不熟悉 graphviz, 有几个困惑, 一起讨论下看看如何尽快解决 🤣

* 困惑 1: graphviz 如何更好地标记“个人推荐”、“其他选项”、“不必严格”等标签
  * 原图里有这些标记, 现在我们怎么转移这份是否推荐的提示?
* 困惑 2: graphviz 无法对原图中的多行备注进行有效的展示
  * 原图里有的备注很长, 怎么转移进来
* 困惑 3: graphviz 如何更好的显示标题
  * 目前我将每个 subgraph 的标题和字内容都并列在相同的缩进中
  * 如果使用在 subgraph 中使用渲染效果也很差
* 困惑 4: graphviz 如何对三层以上进行更好的展示

大家可以一起来讨论下~

**Comment by phodal** [comment]
反馈 3. checklists 这个我看看怎么改 @LiuuY 有建议吗？

graphviz 我再试试

**Comment by LiuuY** [comment]
@phodal 改成 case study 那种（`/case-study/meituan`），`checklists/agile` 之类的

**Comment by phodal** [comment]
可以

**Comment by phodal** [comment]
我感觉可以来一版这个：https://bl.ocks.org/headwinds/4cc120edc973b34c4e569cfdd21b5516

**Comment by phodal** [comment]
duplicated to https://github.com/phodal/ledge/issues/146
