### ISSUE TITLE
模式与原则金字塔等问题

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#17]
1. 顶层文字重叠
![image](https://user-images.githubusercontent.com/22843012/78042890-3f7a5000-73a5-11ea-9f0e-f234835f558a.png)

2. 数据视图点刷新后显示问题
![image](https://user-images.githubusercontent.com/22843012/78042856-34272480-73a5-11ea-8466-1f9d46e6c21b.png)

3. 度量框架，触摸板滑到就自动缩放，体验不好，且缩放后显示不全，没有滚动条。还原缩放后原点位置也变了。。建议减小缩放区域，设置reset
![image](https://user-images.githubusercontent.com/22843012/78043493-fc6cac80-73a5-11ea-8dcb-0a0dd3261fc1.png)
注：其他同类控件也有相同问题

**Comment by phodal** [comment]
问题 2，关了这个功能了
