### ISSUE TITLE
实施手册--Path to DevOps--标题显示不全

### ISSUE THREAD

**Issue by ExDevilLee** [phodal/ledge#170]
如下图所示：
![image](https://user-images.githubusercontent.com/8524336/80304799-fd4cfe80-87ea-11ea-868e-827e12c1de09.png)

**Comment by ExDevilLee** [comment]
HELP: How to add a label for issue?

**Comment by phodal** [comment]
右边

**Comment by ExDevilLee** [comment]
@phodal 可能是因为我没有权限，不能添加tag
