### ISSUE TITLE
Graphviz canvas issue & kanban style

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#175]
1. 流程图的画布可否稍微自适应？有点丑。。
![image](https://user-images.githubusercontent.com/22843012/80517921-603fc080-89b8-11ea-9c87-fbe1b4e3a11a.png)

2. 引用的看板画风有点诡异啊，与我们的风格不统一了，还能抢救不。
类似mermaid/gantt 这俩的风格就好的。
![image](https://user-images.githubusercontent.com/22843012/80518174-b57bd200-89b8-11ea-9731-521aa97fba78.png)

**Comment by phodal** [comment]
1. Graphviz 这个暂时没办法
2. 这个风格不统一，需要找 UX 规划一下？或者你规划一下？

**Comment by giscafer** [comment]
这个流程图不可以用 mermaid 的 flowchart 代替吗？Graphviz 是丑的不忍直视啊

**Comment by phodal** [comment]
@giscafer 你试试？

`src/assets/docs/practises/devops-practise.md` 行数：723
