### ISSUE TITLE
Let checklist-render support inline code & b/i font?

### ISSUE THREAD

**Issue by hylerrix** [phodal/ledge#177]
## Feature Request

在我着手翻译 [API 安全性检查清单(中文版)](https://github.com/shieldfy/API-Security-Checklist/blob/master/README-zh.md) 的时候，发现 checklist render 目前不支持内联代码。

因此想到能否让 checklist render 支持：

- [ ] 加粗语法
- [ ] 斜体语法
- [ ] 内联代码
- [ ] 外链跳转

## What does the proposed API examples?

一个有趣的示例：

```checklist
- API 安全性检查清单
  - **身份认证**
    - _不要_使用 ```Basic Auth```，_请_使用标准的认证协议 (如 [JWT](https://jwt.io/)，OAuth))。
```

渲染效果应该为：

- [ ] API 安全性检查清单
  - [ ] **身份认证**
    - [ ] _不要使用_ ```Basic Auth```，_请_ 使用标准的认证协议 (如 [JWT](https://jwt.io/)，OAuth))。

## Other reference  [Optional]

只是个临时的想法，也没看源码，不知道难不难实现，就试试发这个 issue 一起讨论哈，🤣

**Comment by phodal** [comment]
这应该是个 bug，你先写成 inline 风格的

**Comment by hylerrix** [comment]
以为是个 feature 没想到是个 bug 😁

**Comment by hylerrix** [comment]
新增加了一个：支持 ```[]()``` 链接

**Comment by phodal** [comment]
fixed with https://github.com/phodal/ledge/commit/423216a89c5a386117ab908ba56d28ff43440b93
