### ISSUE TITLE
增加Plantuml支持

### ISSUE THREAD

**Issue by jcwhmn** [phodal/ledge#179]
## Feature Request
希望能增加渲染plantuml的功能

在软件的架构设计或概要设计等过程中，需要使用UML图。如果能渲染在markdown里的uml图，能帮助进行这些软件设计。
## What does the proposed API examples?

现在的VS Code的插件里已有类似的功能：

```
  ```plantuml
    @startuml 状态图 - 外部转换
    [*] -> source
    source -> target : event
    @enduml
  、```
```
这段代码就会生成一个简单的UML状态图

## Other reference  [Optional]

![image](https://user-images.githubusercontent.com/1219310/80571689-a126ec00-8a2f-11ea-8800-af5ac1c3534e.png)

**Comment by phodal** [comment]
试过 `graphviz` 或者 `mermaid` 了吗？

**Comment by jcwhmn** [comment]
没有试过mermaid。plantuml需要graphviz的底层支持。graphviz不能直接画UML图。
mermaid已经直接支持plantuml了吗？

**Comment by phodal** [comment]
我猜你要的这个效果 mermaid 可能能支持

**Comment by jcwhmn** [comment]
我在vs code里试用了一下，不太方便用mermaid来画uml图。
