### ISSUE TITLE
选中样式问题

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#18]
移动端DevOps→测试→UI测试，左侧选中样式显示问题，右侧页面也未跳转至指定位置
![image](https://user-images.githubusercontent.com/22843012/78044156-df84a900-73a6-11ea-935e-33c065489c89.png)

**Comment by ConnieYXN** [comment]
通用问题，原因大概是右侧页面已经显示到最底端了，左侧的选中样式就失效了，其他页面也遇到同样问题。

**Comment by phodal** [comment]
内容太少，所以这个就目前来说是不能右侧同步过去。
