### ISSUE TITLE
[docs]文档的末尾加入源文件跳转链接，方便读者参与勘误或者参与内容编辑

### ISSUE THREAD

**Issue by giscafer** [phodal/ledge#184]
eg：

> 发现错误？想参与编辑？ [在 GitHub 上编辑此页！](https://github.com/phodal/ledge/blob/master/src/assets/docs/reporter.md)

**Comment by kromalee** [comment]
[参考](https://vuepress.vuejs.org/zh/theme/default-theme-config.html#git-%E4%BB%93%E5%BA%93%E5%92%8C%E7%BC%96%E8%BE%91%E9%93%BE%E6%8E%A5)
