### ISSUE TITLE
Home周期表选中问题

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#20]
1. 鼠标快速划过就会弹出选中框，哪怕只是划过页面。建议设置点击才弹出，或设置长一点的停留选中时间
2. 弹出的选中框除了刷新页面，无法关掉，建议点空白处关掉或划过周期表自动关掉
3. 选中框位置固定，不会跟随页面位置变动显示

![image](https://user-images.githubusercontent.com/22843012/78045600-bfee8000-73a8-11ea-959d-5f4dc0c68afb.png)

**Comment by phodal** [comment]
#6

**Comment by phodal** [comment]
move to #38
