### ISSUE TITLE
流程图UI一致性问题

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#21]
所有这类图建议文字居中
![image](https://user-images.githubusercontent.com/22843012/78046094-4e630180-73a9-11ea-8693-9ca185b470d4.png)

如下图，字折行了，几个文字出框了，下面黑框里应该是什么字？
![image](https://user-images.githubusercontent.com/22843012/78050981-a1d84e00-73af-11ea-81d1-fdf4e2ac83a1.png)

**Comment by phodal** [comment]
下面这个本来是空的。上面那个居中，估计是一个 bug  了

**Comment by phodal** [comment]
这个有了新的 UI 了， https://github.com/phodal/ledge/issues/53
