### ISSUE TITLE
Ledge编辑器:代码与预览的交互功能

### ISSUE THREAD

**Issue by kromalee** [phodal/ledge#213]
## Feature Request

-   调整预览里面的可操作控件时,代码也应该同步变化
> 例如 看板里面的项目 拖动,代码里的项目也应该同步变化

**Comment by phodal** [comment]
这个是不打算有的，因为真实的文档是不会同步回去的

**Comment by kromalee** [comment]
> 这个是不打算有的，因为真实的文档是不会同步回去的

这个作为编辑器的功能应该可以吧
