### ISSUE TITLE
Icinga的内容描述是Sensu的

### ISSUE THREAD

**Issue by zerlier** [phodal/ledge#221]
{
    "name": "Sensu",
    "category": "monitoring",
    "number": 60,
    "homepage": "https://sensu.io/",
    "description": "Sensu 是由 Sonian 公司开发的一种监控框架，主要用于拥有大规模节点的云计算平台的检查与监控。",
    "pay": "Os",
    "symbol": "Ss"
  },
  {
    "name": "Icinga",
    "category": "monitoring",
    "number": 61,
    "description": "Sensu 是由 Sonian 公司开发的一种监控框架，主要用于拥有大规模节点的云计算平台的检查与监控。",
    "homepage": "https://icinga.com/",
    "pay": "Os",
    "symbol": "Ic"
  },

**Comment by phodal** [comment]
欢迎来 PR 修复
