### ISSUE TITLE
Markdown扩展语法  syntax see in ledge render    无法跳转

### ISSUE THREAD

**Issue by Nibbbbbbbb** [phodal/ledge#230]
## Bug Report

首页README.md中的 

- Markdown扩展语法  
	- syntax see in [ledge render](https://github.com/phodal/ledge/blob/master/projects/@ledge-framework/render)    无法跳转

## Current Behavior?
404 无法跳转 https://github.com/phodal/ledge/blob/master/projects/@ledge-framework/render

**Comment by phodal** [comment]
相关的项目放到： https://github.com/ledge-framework 里了，要来个 pr 吗？
