### ISSUE TITLE
GitOps: 一种云原生时代的DevOps实践

### ISSUE THREAD

**Issue by Cactusinhand** [phodal/ledge#249]
## Feature Request
希望增加有关GitOps的内容：
- https://www.weave.works/blog/gitops-operations-by-pull-request
- https://www.escapelife.site/posts/117cbee7.html#!
- https://www.atlassian.com/git/tutorials/gitops

**Comment by phodal** [comment]
要来 PR ？

**Comment by Cactusinhand** [comment]
> 要来 PR ？

暂时无精力😞
