### ISSUE TITLE
设计 DevOps，Add & Remove 按钮 issue

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#25]
设计 DevOps，
1. 把所有元素都Remove掉，再多点几下Remove，再点Add，你就发现了个数支持负数~
2. 添加多个元素时，顶端样式和按钮可以跟过去不？
![image](https://user-images.githubusercontent.com/22843012/78048497-638d5f80-73ac-11ea-900a-9a3e5b573197.png)

**Comment by phodal** [comment]
duplicated #84
