### ISSUE TITLE
 Spacewalk has stoped in 2020

### ISSUE THREAD

**Issue by AntiVirusGo** [phodal/ledge#251]
##  Spacewalk has stoped in 2020

In [LEDGE](https://devops.phodal.com/home)'s Index html, it appears there is a Security Tool in the chart called Spacewalk. 
I viewed the web-site [spacewalkproject](https://spacewalkproject.github.io/), It declared that Spacewalk project has been discontinued on May 31 2020.
So i suggested that we can delete such a non-existed project from the chart.

**Comment by phodal** [comment]
welcome to give a pr to remove it~
