### ISSUE TITLE
树图最小化后没法放大了

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#28]
如下图，树图不小心最小化了，无法恢复
![image](https://user-images.githubusercontent.com/22843012/78051321-17441e80-73b0-11ea-8d2b-d70a2ee52cdb.png)

**Comment by phodal** [comment]
@Jooeys Echart 是不是你最熟了

**Comment by LiuuY** [comment]
最小化之后，需要鼠标放到👇，再滚动才能缩放，这个是 ECharts 自己的逻辑。
![image](https://user-images.githubusercontent.com/14286374/78225515-ecb3ac00-74fc-11ea-8e04-84984598bf0d.png)
