### ISSUE TITLE
support IE11+

### ISSUE THREAD

**Issue by LiuuY** [phodal/ledge#3]

**Comment by phodal** [comment]
marked.js 0.8.0，导致 ngx-marked.js 不支持 IE 11。

https://github.com/markedjs/marked/issues/1585
https://github.com/jfcere/ngx-markdown/issues/210

**Comment by LiuuY** [comment]
可以把 Markdown 本地编译好 SSR？

**Comment by phodal** [comment]
可以，可以是个好主意

**Comment by phodal** [comment]
https://github.com/markedjs/marked/issues/1630

**Comment by phodal** [comment]
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/472311/80486493-d549d080-898d-11ea-93fb-b1993355e992.png">

IE 用户不到 1%，暂时不考虑了
