### ISSUE TITLE
右侧滚动条不一致

### ISSUE THREAD

**Issue by LiuuY** [phodal/ledge#5]
有的页面 header fix 在顶部，有的跟随滚动。

![image](https://user-images.githubusercontent.com/14286374/77918102-00c59680-72ce-11ea-86c8-6eaaea3e9cb2.png)

![image](https://user-images.githubusercontent.com/14286374/77918130-0ae79500-72ce-11ea-8d8b-692dd56940f1.png)

**Comment by phodal** [comment]
fixed with #12
