### ISSUE TITLE
DevOps 元素周期表色块的点击事件设置详情

### ISSUE THREAD

**Issue by Jooeys** [phodal/ledge#6]
- 部分元素色块没有基本的描述信息，没有设置相关的跳转链接，比如给具体repo等。
- 或可增加点击元素跳转到具体使用案例等。

**Comment by phodal** [comment]
类似于？ http://sherlock.phodal.com/

**Comment by Jooeys** [comment]
> 类似于？ http://sherlock.phodal.com/

是的，感觉这样做知识图谱，让阅读者很容易自我延伸拓展溯源下去 🐶

**Comment by phodal** [comment]
可以，可以，你要不试试？

**Comment by Jooeys** [comment]
> 可以，可以，你要不试试？

已悄悄Fork ,不过只用过echart.js,希望有能力给大佬的项目提PR
