### ISSUE TITLE
New render issue

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#60]
1. list-style，多余4个节点时，样式缺失（浅绿色是选中色，不选中就啥都看不见），换行错位
![image](https://user-images.githubusercontent.com/22843012/78500028-c30db580-7786-11ea-95bf-d541603ba503.png)

2. list-style，是否支持二级标题？看缩进像是支持，但文字内容多时看不出层级关系；circle时二级标题没显示，但配置了二级标题的circle明显和另外两个width不同。

![image](https://user-images.githubusercontent.com/22843012/78500160-90b08800-7787-11ea-9346-5d45dab6284d.png)

3. quadrant仍然能点，随意飞走~~~
4. mindmap不能直接显示全部了，滑动调整又会触发缩放。。能否提供 展开、收起 按钮
5. radar的标题不显示了

**Comment by phodal** [comment]
2. 不支持二级标题。
