### ISSUE TITLE
周期表issue

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#73]
1. 周期表图例选择范围过大，选择 dk 或 k8 时，经常触发图例的选择，导致一类色块显示黑色。
2. 图例选择指针手势为光标，建议改成点击手势。
3. 元素格内的滚动条在格外面，建议调整样式，另外格内文字缺少边距。如果是呼出的格子，可以调整稍微大一点。
![image](https://user-images.githubusercontent.com/22843012/78733450-18f57f80-7978-11ea-80e8-9acd6a0c7796.png)

**Comment by phodal** [comment]
哦，对，好像是 13 的屏幕太小了

**Comment by phodal** [comment]
问题1，暂时无解
