### ISSUE TITLE
Should have back to top button in case study page

### ISSUE THREAD

**Issue by tobyqin** [phodal/ledge#77]
**Describe the bug**
Should have back to top button on case study page

**To Reproduce**
1. Go to case study page, choose any case, e.g. https://devops.phodal.com/case-study?source=meituan
2. Scroll down to page bottom

**Expected behavior**
Should have back to top button

**Desktop (please complete the following information):**
 - OS: OSX 10,15.4
 - Browser chrome
 - Version [80]

**Comment by phodal** [comment]
欢迎来 PR，哈哈
