### ISSUE TITLE
Should have better side menu in content page

### ISSUE THREAD

**Issue by tobyqin** [phodal/ledge#79]
**Describe the bug**
Should have better side menu in content page

**To Reproduce**
1. Go to https://devops.phodal.com/pattern
2. Check the side menu

**Expected behavior**
- Should be designed, now it looks ugly

**Screenshots**
![image](https://user-images.githubusercontent.com/14037644/78796087-74f7ec80-79e8-11ea-86d1-e201c56b4bb4.png)

**Desktop (please complete the following information):**
 - OS: OSX 10,15.4
 - Browser chrome
 - Version [80]

**Comment by phodal** [comment]
update with https://github.com/phodal/ledge/commit/4373e74188feb2d6a10203738612880888341207 replaced with 107
