### ISSUE TITLE
Should use same pattern for side menus

### ISSUE THREAD

**Issue by tobyqin** [phodal/ledge#81]
**Expected behavior**
They should be in same pattern.

**Screenshots**
case study page
![image](https://user-images.githubusercontent.com/14037644/78796889-8c83a500-79e9-11ea-842b-fc39837dab5f.png)

patterns page
![image](https://user-images.githubusercontent.com/14037644/78796912-960d0d00-79e9-11ea-92c4-69a4861d859a.png)

solutions page
![image](https://user-images.githubusercontent.com/14037644/78797395-38c58b80-79ea-11ea-930a-7ec83852baaf.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser chrome
 - Version 80

**Comment by phodal** [comment]
这个好像比较难，估计要重新设计一下，区分一下两种场景

**Comment by tobyqin** [comment]
目前感觉有点分裂
可能资料类页面的菜单项目会比较多，而且是自动生成的，可不可以考虑自动隐藏子菜单，比如 https://docsify.now.sh/configuration

当你点击Configuration才会出现子菜单

**Comment by phodal** [comment]
不错，可以考虑，主要是没人……

**Comment by LiuuY** [comment]
需要 UX 设计一个新的 Menu
