### ISSUE TITLE
Menu item should not break to new line

### ISSUE THREAD

**Issue by tobyqin** [phodal/ledge#82]
1. Go to https://devops.phodal.com/pattern#architecture-dashboard
2. Scroll down to page bottom
3. See screenshot

**Expected behavior**
The menu item should not break into new line

**Screenshots**
![image](https://user-images.githubusercontent.com/14037644/78797621-82ae7180-79ea-11ea-8e03-8f0a9482caef.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 80

**Comment by phodal** [comment]
这个……好像有点难，我们重新设计一下
