### ISSUE TITLE
设计 DevOps Issue

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#84]
**Describe the bug**
1️⃣设计 Devops，Reset 按钮在特定情况下失效：
1. Remove两次以后
2. Add两次以后
3. Remove + Add 各一次后

2️⃣强刷，直接Remove，再Add，会发现Add带上刚Remove的节点。

3️⃣随着Remove，会增加行高，不理解...
![image](https://user-images.githubusercontent.com/22843012/78812689-63b9da80-79fe-11ea-84e6-cc7f97cff22e.png)

4️⃣按钮位置、按钮背景样式、菜单样式写固定了，当出现滚动条时，应随滚动条总在最右。现在按钮点一下会跳位置。
![image](https://user-images.githubusercontent.com/22843012/78813095-17bb6580-79ff-11ea-8eaf-d9635c29e35b.png)

**Comment by phodal** [comment]
这个之前的还没修，那我就都关联上吧 #25 && #26
