### ISSUE TITLE
Sub-menu issue

### ISSUE THREAD

**Issue by ConnieYXN** [phodal/ledge#86]
两个带子菜单的根菜单切换时，需要点两下，第一下先把子菜单列表点没，第二下才能显示新的子菜单。建议点一下搞定。
![image](https://user-images.githubusercontent.com/22843012/78813680-f7d87180-79ff-11ea-9e47-4b0a1cce0188.png)

**Comment by phodal** [comment]
这个组件库是这么设计的，好像用户习惯都是这样的，23

**Comment by phodal** [comment]
改不动啊，组件库设计 + 用户习惯如此
